### ISSUE TITLE
Transferring Account Details

### ISSUE THREAD

**Issue by BrettDowneyuofm** [gilhrpenner/COMP4350#37]
Account details should be transmitted from the frontend to the backend securely. 

Passwords should be hashed before being submitted to the backend.

A token should be used in order to maintain the login state.

**Comment by gilhrpenner** [comment]
Just to clarify this task, are we sure we want to hash the password on the client side before sending it over to the backend?

I think that's a security issue
- Everything sent on a SSL connection is encrypted
- if we hash the password on client side then we lose control of hashing things such as salt, etc.
- the backend would essentially be saving the "raw password" since it would be hashed client side

@BrettDowneyuofm @akashd50

**Comment by gilhrpenner** [comment]
Another thing that I wanted to bring up is the usage of jwt (json web tokens) for authentication.

Short summary of jwt's to keep everyone in the same page
- Simple and safe to use, we take a js object and we encrypt it with a signature to ensure it was generated by us
- The js object is easy to decrypt so no sensitive data should be there such as password even if hashed
- backend will be the only place with the signature token so it is indeed safe

pros:
- stateless server
- less resources
- less work for us
- faster responses since we don't need to check database or anything

cons:
- jwt once generated will be alive for the duration of its lifespan, so if we generate a token for 365 days, even if the user sign-out or change the password the token will still be valid

A way to prevent the above problem is setting the lifespan of the token short, like 15 minutes, and every interaction with the backend we generate a new token, since we already have to send a response to the client we inject the new jwt there, easy and simple to do.

Will this solve the problem of user changing the password or signing-out? No, but it will be less of an issue and to be honest for the scope of this project and even real life scenarios it is still a widely used authentication method. There are other steps we can include with the jwt to make it even more safe but tbh this is way beyond the scope of 4350 and I am damn sure we wouldn't have any security issues or even lose marks with it.

But hey, are there any other solutions? Absolutely, we can use server sessions

How it works:
- Create a session server side and send back a cookie with the session id to the client
- Client will always send the cookie, just like the jwt, server then proceeds to check if there is a valid session for that id

pros:
- solves al the problems I mentioned about jwt 

cons:
- Way more work, we need to set a database or a redis server for that so it can be super fast and not impact in response time
- Need to setup a service and repository to handle all of that, besides what we would normally do for jwt tokns.

It is a bit more of work for us but solves the problems with jwt.
Will it be safer and give us more marks? I don't think so.

Ultimately is up to y'all, I am good for both solutions but lean towards jwt just because it is easier to work with.

Gimme your thoughts, this would be the next thing I will be working on so need insights before I lose my precious time :)


@akashd50 @BrettDowneyuofm  @MarkRobitaille

**Comment by BrettDowneyuofm** [comment]
> Just to clarify this task, are we sure we want to hash the password on the client side before sending it over to the backend?
> 
> I think that's a security issue
> 
>     * Everything sent on a SSL connection is encrypted
> 
>     * if we hash the password on client side then we lose control of hashing things such as salt, etc.
> 
>     * the backend would essentially be saving the "raw password" since it would be hashed client side
> 
> 
> @BrettDowneyuofm @akashd50

You're right, in the past I've implemented client side hashing first, then server side hashing afterwards. Therefore the server will never receive the plain text password from the user. But for this case I don't think it'll be needed so the hashing can just be done by the backend.
